### ISSUE TITLE
Doesn't work on non-sourcegraph repositories

### ISSUE THREAD

**Issue by ruairidhwm** [sourcegraph/sourcegraph-test-leaderboard#5]
Hi,

This doesn't seem to work for non-sourcegraph repositories. It looks like it's related to this line: https://github.com/sourcegraph/sourcegraph-test-leaderboard/blob/b9ccbc12052220c38fec14efea4677d3b2a4127e/src/sourcegraph-test-leaderboard.ts#L41.

Is there a reason for it being scoped to sourcegraph repositories, and if not, could this be changed?

Thanks

**Comment by sqs** [comment]
No reason. This was just to "feature-flag" it. We can remove it. If you want to submit a PR to remove it, that would be great!

**Comment by ruairidhwm** [comment]
Great! I've PR'd the change:  #6
